# Generated by Django 5.1.1 on 2024-10-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
