# Generated by Django 5.1.1 on 2024-10-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0004_remove_propertyimage_property_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('user_type', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('owner', 'Owner')], default='user', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('legal_document', models.FileField(blank=True, null=True, upload_to='legal_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
