# Generated by Django 5.1.1 on 2024-10-10 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('for_property', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10)),
                ('type_property', models.CharField(choices=[('residential', 'Residential'), ('lease', 'Lease'), ('commercial', 'Commercial')], max_length=12)),
                ('usage', models.CharField(choices=[('office', 'For Office'), ('shop', 'For Shop'), ('restaurant', 'For Restaurant')], max_length=12)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('subcity_zone', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('floor_level', models.CharField(max_length=20)),
                ('total_area', models.FloatField()),
                ('area', models.FloatField()),
                ('google_map_link', models.URLField()),
                ('living_rooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('kitchens', models.IntegerField()),
                ('built_date', models.DateField()),
                ('number_of_balconies', models.IntegerField()),
                ('average_price_per_square_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('computing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('features_and_amenities', models.TextField()),
                ('heating_type', models.CharField(choices=[('gas', 'Gas'), ('electric', 'Electric')], max_length=20)),
                ('cooling', models.CharField(choices=[('AC', 'AC'), ('electric', 'Electric')], max_length=20)),
                ('nearest_residential', models.TextField()),
                ('own_description', models.TextField()),
                ('video', models.URLField(blank=True, null=True)),
                ('link_to_video_or_image', models.URLField(blank=True, null=True)),
                ('ownership_of_property', models.FileField(upload_to='ownership_files/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.customer')),
            ],
        ),
    ]
