# Generated by Django 5.1.1 on 2024-11-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_tour_telegram_id_tour_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_post_url', models.URLField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.property')),
            ],
            options={
                'unique_together': {('customer', 'property')},
            },
        ),
    ]
